/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideContainer: typeof import('./components/AsideContainer.vue')['default']
    BaseContainer: typeof import('./components/BaseContainer.vue')['default']
    BtnGroup: typeof import('./components/BtnGroup.vue')['default']
    Chat: typeof import('./views/Chat.vue')['default']
    ChatAside: typeof import('./components/ChatAside.vue')['default']
    ChatHeader: typeof import('./components/ChatHeader.vue')['default']
    ChatItem: typeof import('./components/ChatItem.vue')['default']
    ChatLayout: typeof import('./components/ChatLayout.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    ChatWrapper: typeof import('./components/ChatWrapper.vue')['default']
    MainContainer: typeof import('./components/MainContainer.vue')['default']
    Paper: typeof import('./components/Paper.vue')['default']
    RecentChatWrapper: typeof import('./components/RecentChatWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./components/ScrollArea.vue')['default']
    SelectModelModal: typeof import('./components/SelectModelModal.vue')['default']
    StreamContent: typeof import('./components/StreamContent.vue')['default']
    Translate: typeof import('./views/Translate.vue')['default']
    UserChatMessage: typeof import('./components/UserChatMessage.vue')['default']
    WordExplain: typeof import('./components/WordExplainPaper.vue')['default']
    WordExplainPaper: typeof import('./components/WordExplainPaper.vue')['default']
  }
}
